AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
  Api:
      BinaryMediaTypes:
         - '*~1*'

Resources: 
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: 'mentoringprojectgabriel-uploadedfiles'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false

  UploadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: image-uploader/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Layers:
        - !Ref DependenciesLayer       
      Events:
        Upload:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /upload
            Method: post
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:PutObjectACL
              Resource: 'arn:aws:s3:::mentoringprojectgabriel-uploadedfiles/*' 

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dependencies.zip
      # ContentUri: dependencies/

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UploadApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload/"
  UploadFunction:
    Description: "Upload Lambda Function ARN"
    Value: !GetAtt UploadFunction.Arn
  UploadFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt UploadFunctionRole.Arn
